(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  else root.SoundScopeOrbitShare = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";

  const WIDTH = 1080; const HEIGHT = 1920; const FILE_NAME = "soundscope-minha-orbita.png"; const MAX_ARTISTS = 5;
  const POSITIONS = [{ x: 540, y: 680, r: 180 }, { x: 260, y: 460, r: 108 }, { x: 835, y: 455, r: 96 }, { x: 205, y: 875, r: 88 }, { x: 850, y: 850, r: 92 }];
  function selectArtists(items) { return (Array.isArray(items) ? items : []).slice(0, MAX_ARTISTS).map((artist, index) => ({ name: String(artist?.name || "Artista não informado"), image: typeof artist?.image === "string" && /^https:\/\//.test(artist.image) ? artist.image : "", rank: index + 1 })); }
  function initials(name) { return String(name).trim().split(/\s+/).slice(0, 2).map((part) => part[0] || "").join("").toUpperCase() || "?"; }
  function truncate(ctx, value, maxWidth) { let text = String(value); if (ctx.measureText(text).width <= maxWidth) return text; while (text.length && ctx.measureText(`${text}…`).width > maxWidth) text = text.slice(0, -1); return `${text}…`; }
  function text(ctx, value, x, y, options = {}) { ctx.save(); ctx.fillStyle = options.color || "#f2f3f4"; ctx.font = `${options.weight || 500} ${options.size || 24}px ${options.family || "Manrope, sans-serif"}`; ctx.textAlign = options.align || "left"; ctx.textBaseline = options.baseline || "alphabetic"; if (options.letterSpacing && typeof ctx.letterSpacing !== "undefined") ctx.letterSpacing = `${options.letterSpacing}px`; ctx.fillText(value, x, y); ctx.restore(); }
  function wrapText(ctx, value, x, y, maxWidth, lineHeight, options = {}) { const words = String(value).split(/\s+/); let line = ""; const lines = []; words.forEach((word) => { const attempt = line ? `${line} ${word}` : word; if (line && ctx.measureText(attempt).width > maxWidth) { lines.push(line); line = word; } else line = attempt; }); if (line) lines.push(line); lines.slice(0, options.maxLines || lines.length).forEach((item, index) => text(ctx, item, x, y + index * lineHeight, options)); return lines.length; }
  function circle(ctx, x, y, radius, fill, stroke) { ctx.beginPath(); ctx.arc(x, y, radius, 0, Math.PI * 2); if (fill) { ctx.fillStyle = fill; ctx.fill(); } if (stroke) { ctx.strokeStyle = stroke; ctx.lineWidth = 2; ctx.stroke(); } }
  function line(ctx, x1, y1, x2, y2, color = "rgba(98,138,154,.24)") { ctx.beginPath(); ctx.moveTo(x1, y1); ctx.lineTo(x2, y2); ctx.strokeStyle = color; ctx.lineWidth = 2; ctx.stroke(); }
  function fallbackArtist(ctx, artist, position) { circle(ctx, position.x, position.y, position.r, "#151a20", "rgba(98,138,154,.55)"); text(ctx, initials(artist.name), position.x, position.y, { size: Math.round(position.r * .48), color: "#83a4b0", align: "center", baseline: "middle" }); }
  function circularImage(ctx, image, position) { ctx.save(); ctx.beginPath(); ctx.arc(position.x, position.y, position.r, 0, Math.PI * 2); ctx.clip(); ctx.drawImage(image, position.x - position.r, position.y - position.r, position.r * 2, position.r * 2); ctx.restore(); circle(ctx, position.x, position.y, position.r, null, "rgba(255,255,255,.2)"); }
  function containedImage(ctx, image, x, y, maxWidth, maxHeight) { const width = image.naturalWidth || image.width || maxWidth; const height = image.naturalHeight || image.height || maxHeight; const scale = Math.min(maxWidth / width, maxHeight / height); const drawWidth = width * scale; const drawHeight = height * scale; ctx.drawImage(image, x + (maxWidth - drawWidth) / 2, y + (maxHeight - drawHeight) / 2, drawWidth, drawHeight); }
  function loadImage(src, ImageClass) { return new Promise((resolve) => { if (!src || !ImageClass) { resolve(null); return; } const image = new ImageClass(); image.crossOrigin = "anonymous"; image.onload = () => resolve(image); image.onerror = () => resolve(null); image.src = src; }); }
  async function render(canvas, items, options = {}) {
    if (!canvas) throw new Error("CANVAS_REQUIRED"); canvas.width = WIDTH; canvas.height = HEIGHT;
    const ctx = canvas.getContext("2d"); const artists = selectArtists(items); const ImageClass = options.ImageClass || (typeof Image !== "undefined" ? Image : null);
    if (typeof document !== "undefined" && document.fonts?.ready) await document.fonts.ready;
    const [icon, ...images] = await Promise.all([loadImage(options.iconUrl || "assets/soundscope-icon-512.png", ImageClass), ...artists.map((artist) => loadImage(artist.image, ImageClass))]);
    ctx.fillStyle = "#0b0d10"; ctx.fillRect(0, 0, WIDTH, HEIGHT);
    const gradient = ctx.createRadialGradient(540, 660, 50, 540, 660, 650); gradient.addColorStop(0, "rgba(98,138,154,.14)"); gradient.addColorStop(1, "rgba(11,13,16,0)"); ctx.fillStyle = gradient; ctx.fillRect(0, 0, WIDTH, 1320);
    if (icon) { containedImage(ctx, icon, 76, 72, 52, 52); text(ctx, "SoundScope", 148, 99, { size: 29, weight: 600, baseline: "middle" }); }
    else text(ctx, "SoundScope", 76, 99, { size: 29, weight: 600, baseline: "middle" });
    text(ctx, "MINHA ÓRBITA MUSICAL", 1004, 108, { size: 17, color: "#879096", align: "right", letterSpacing: 3 }); line(ctx, 76, 160, 1004, 160, "rgba(255,255,255,.12)");
    circle(ctx, 540, 680, 330, null, "rgba(255,255,255,.05)"); circle(ctx, 540, 680, 455, null, "rgba(98,138,154,.08)");
    artists.forEach((artist, index) => { if (index) line(ctx, 540, 680, POSITIONS[index].x, POSITIONS[index].y); });
    artists.forEach((artist, index) => { const position = POSITIONS[index]; if (images[index]) circularImage(ctx, images[index], position); else fallbackArtist(ctx, artist, position); text(ctx, String(index + 1).padStart(2, "0"), position.x, position.y + position.r + 34, { size: 15, color: "#7398a6", align: "center", letterSpacing: 2 }); text(ctx, truncate(ctx, artist.name, index === 0 ? 430 : 250), position.x, position.y + position.r + 68, { size: index === 0 ? 27 : 21, align: "center" }); });
    line(ctx, 76, 1165, 1004, 1165, "rgba(255,255,255,.12)"); text(ctx, "SEU UNIVERSO MUSICAL", 76, 1235, { size: 18, color: "#7398a6", letterSpacing: 4 });
    artists.forEach((artist, index) => { const y = 1320 + index * 88; text(ctx, String(index + 1).padStart(2, "0"), 76, y, { size: 16, color: "#7398a6", letterSpacing: 2 }); text(ctx, truncate(ctx, artist.name, 780), 150, y, { size: 31 }); line(ctx, 76, y + 35, 1004, y + 35, "rgba(255,255,255,.055)"); });
    line(ctx, 76, 1770, 1004, 1770, "rgba(255,255,255,.12)"); text(ctx, "SOUNDSCOPE", 76, 1835, { size: 24, letterSpacing: 4 }); text(ctx, "Descubra o som por trás do nome.", 1004, 1835, { size: 18, color: "#879096", align: "right" });
    return { canvas, artists, imageFallbacks: images.filter((image) => !image).length };
  }
  function canvasToBlob(canvas) { return new Promise((resolve, reject) => canvas.toBlob((blob) => blob ? resolve(blob) : reject(new Error("PNG_GENERATION_FAILED")), "image/png")); }
  function createFile(blob, FileClass) { const Constructor = FileClass || (typeof File !== "undefined" ? File : null); return Constructor ? new Constructor([blob], FILE_NAME, { type: "image/png" }) : { name: FILE_NAME, type: "image/png", blob }; }
  function download(blob, documentObject = typeof document !== "undefined" ? document : null, URLObject = typeof URL !== "undefined" ? URL : null) { const href = URLObject.createObjectURL(blob); const anchor = documentObject.createElement("a"); anchor.href = href; anchor.download = FILE_NAME; documentObject.body.append(anchor); anchor.click(); anchor.remove(); URLObject.revokeObjectURL(href); }
  async function shareOrDownload(blob, navigatorObject = typeof navigator !== "undefined" ? navigator : {}, dependencies = {}) { const file = createFile(blob, dependencies.FileClass); if (typeof navigatorObject.share === "function" && typeof navigatorObject.canShare === "function" && navigatorObject.canShare({ files: [file] })) { await navigatorObject.share({ files: [file], title: "Minha Órbita — SoundScope" }); return "shared"; } (dependencies.download || download)(blob); return "downloaded"; }
  function mount(container, options = {}) {
    if (!container) return null; const canvas = container.querySelector("[data-share-canvas]"); const status = container.querySelector("[data-share-status]"); const generateButton = container.querySelector("[data-share-generate]"); const downloadButton = container.querySelector("[data-share-download]"); const shareButton = container.querySelector("[data-share-share]"); const closeButtons = container.querySelectorAll("[data-share-close]");
    let artists = []; let blob = null; let opener = null; let busy = false; const focusable = () => [...container.querySelectorAll("button:not([disabled])")];
    async function generate() { if (busy) return null; busy = true; status.textContent = "Gerando imagem…"; generateButton.disabled = true; try { await render(canvas, artists, options); blob = await canvasToBlob(canvas); downloadButton.disabled = false; shareButton.disabled = false; status.textContent = "Story pronto. Você pode baixar ou abrir o compartilhamento do dispositivo."; return blob; } catch (_) { status.textContent = "Não foi possível gerar a imagem. Tente novamente."; return null; } finally { busy = false; generateButton.disabled = false; } }
    function close() { container.classList.add("is-hidden"); container.setAttribute("aria-hidden", "true"); document.body.classList.remove("orbit-share-open"); opener?.focus?.(); }
    function open(items, trigger) { artists = selectArtists(items); if (!artists.length) return false; blob = null; opener = trigger || document.activeElement; downloadButton.disabled = true; shareButton.disabled = true; status.textContent = ""; container.classList.remove("is-hidden"); container.setAttribute("aria-hidden", "false"); document.body.classList.add("orbit-share-open"); container.querySelector(".orbit-share__close").focus(); render(canvas, artists, options).catch(() => {}); return true; }
    function onKeydown(event) { if (container.classList.contains("is-hidden")) return; if (event.key === "Escape") { event.preventDefault(); close(); return; } if (event.key === "Tab") { const nodes = focusable(); const first = nodes[0]; const last = nodes.at(-1); if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } } }
    generateButton.addEventListener("click", generate); downloadButton.addEventListener("click", async () => { const output = blob || await generate(); if (output) { (options.download || download)(output); status.textContent = "PNG baixado."; } }); shareButton.addEventListener("click", async () => { const output = blob || await generate(); if (!output) return; try { const result = await shareOrDownload(output, options.navigator, { FileClass: options.FileClass, download: options.download }); status.textContent = result === "shared" ? "Arquivo entregue ao compartilhamento do dispositivo." : "Compartilhamento de arquivos indisponível. PNG baixado."; } catch (error) { if (error?.name !== "AbortError") status.textContent = "O compartilhamento não foi concluído. Você ainda pode baixar o PNG."; } }); closeButtons.forEach((button) => button.addEventListener("click", close)); document.addEventListener("keydown", onKeydown);
    return { open, close, generate, setArtists(items) { artists = selectArtists(items); }, getArtists() { return [...artists]; } };
  }
  return { WIDTH, HEIGHT, FILE_NAME, MAX_ARTISTS, selectArtists, initials, truncate, loadImage, render, canvasToBlob, createFile, download, shareOrDownload, mount };
});
